export const categorySymbols = {
  "General Knowledge": "/categories/symbol_general.png",
  "Entertainment: Books": "/categories/symbol_book.png",
  "Entertainment: Film": "/categories/symbol_movie.png",
  "Entertainment: Music": "/categories/symbol_music.png",
  "Entertainment: Musicals & Theatres": "/categories/symbol_theater.png",
  "Entertainment: Television": "/categories/symbol_tv.png",
  "Entertainment: Video Games": "/categories/symbol_vgames.png",
  "Entertainment: Board Games": "/categories/symbol_bgames.png",
  "Science & Nature": "/categories/symbol_scienceN.png",
  "Science: Computers": "/categories/symbol_pc.png",
  "Science: Mathematics": "/categories/symbol_math.png",
  Mythology: "/categories/symbol_myth.png",
  Sports: "/categories/symbol_sport.png",
  Geography: "/categories/symbol_geo.png",
  History: "/categories/symbol_history.png",
  Politics: "/categories/symbol_politics.png",
  Art: "/categories/symbol_art.png",
  Celebrities: "/categories/symbol_celeb.png",
  Animals: "/categories/symbol_animal.png",
  Vehicles: "/categories/symbol_vehicles.png",
  "Entertainment: Comics": "/categories/symbol_comics.png",
  "Science: Gadgets": "/categories/symbol_gadgets.png",
  "Entertainment: Japanese Anime & Manga": "/categories/symbol_anime.png",
  "Entertainment: Cartoon & Animations": "/categories/symbol_cartoon.png",
};
