export const categorySymbols = {
  "General Knowledge": "src/images/categories/symbol_general.png",
  "Entertainment: Books": "src/images/categories/symbol_book.png",
  "Entertainment: Film": "src/images/categories/symbol_movie.png",
  "Entertainment: Music": "src/images/categories/symbol_music.png",
  "Entertainment: Musicals & Theatres": "src/images/categories/symbol_theater.png",
  "Entertainment: Television": "src/images/categories/symbol_tv.png",
  "Entertainment: Video Games": "src/images/categories/symbol_vgames.png",
  "Entertainment: Board Games": "src/images/categories/symbol_bgames.png",
  "Science & Nature": "src/images/categories/symbol_scienceN.png",
  "Science: Computers": "src/images/categories/symbol_pc.png",
  "Science: Mathematics": "src/images/categories/symbol_math.png",
  "Mythology": "src/images/categories/symbol_myth.png",
  "Sports": "src/images/categories/symbol_sport.png",
  "Geography": "src/images/categories/symbol_geo.png",
  "History": "src/images/categories/symbol_history.png",
  "Politics": "src/images/categories/symbol_politics.png",
  "Art": "src/images/categories/symbol_art.png",
  "Celebrities": "src/images/categories/symbol_celeb.png",
  "Animals": "src/images/categories/symbol_animal.png",
  "Vehicles": "src/images/categories/symbol_vehicles.png",
  "Entertainment: Comics": "src/images/categories/symbol_comics.png",
  "Science: Gadgets": "src/images/categories/symbol_gadgets.png",
  "Entertainment: Japanese Anime & Manga": "src/images/categories/symbol_anime.png",
  "Entertainment: Cartoon & Animations": "src/images/categories/symbol_cartoon.png",
};
