export const categorySymbols = {
    "9": "src/images/categories/symbol_general.png",
    "10": "src/images/categories/symbol_book.png",
    "11": "src/images/categories/symbol_movie.png",
    "12": "src/images/categories/symbol_music.png",
    "13": "src/images/categories/symbol_theater.png",
    "14": "src/images/categories/symbol_tv.png",
    "15": "src/images/categories/symbol_vgames.png",
    "16": "src/images/categories/symbol_bgames.png",
    "17": "src/images/categories/symbol_scienceN.png",
    "18": "src/images/categories/symbol_pc.png",
    "19": "src/images/categories/symbol_math.png",
    "20": "src/images/categories/symbol_myth.png",
    "21": "src/images/categories/symbol_sport.png",
    "22": "src/images/categories/symbol_geo.png",
    "23": "src/images/categories/symbol_history.png",
    "24": "src/images/categories/symbol_politics.png",
    "25": "src/images/categories/symbol_art.png",
    "26": "src/images/categories/symbol_celeb.png",
    "27": "src/images/categories/symbol_animal.png",
};